# Generated by Django 4.2.6 on 2023-10-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('qtt', models.BigIntegerField(default=0)),
                ('preco_venda', models.FloatField(default=350.0)),
                ('preco_custo', models.FloatField(default=270.0)),
                ('pedidos', models.BigIntegerField(default=0)),
            ],
        ),
    ]
